ALLOWED_COMMANDS = [
    # Mouse buttons
    "click",
    "right click",
    "middle click",
    "double click",
    "heat",
    # Modifier key hold/release
    "control down",
    "control up",
    "shift down",
    "shift up",
    "alt down",
    "alt up",
    # Wake / sleep
    "go to sleep",
    "sleep",        # fallback for when "go to" is swallowed by mic/VAD
    # Write mode
    "writing mode",
    # Keystroke passthrough
    "press",
    # Release held keys / mouse buttons
    "release",
    "release all",
    "release all keys",
    "release left click",
    "release right click",
    "release middle click",
    # Hybrid trigger words (Vosk captures keyword, Whisper captures payload)
    "move",
    "gain",
    # File
    "screenshot",
    "new project",
    "new sequence",
    "open project",
    "close",
    "close project",
    "save",
    "save as",
    "save a copy",
    "import from media browser",
    "import",
    "export",
    "encoder",
    "properties",
    "exit",
    "shortcuts",
    "production",
    "refresh",
    "poster",
    "close sequence",
    "close tab",
    "color properties",
    "bin from selection",
    "new smart bin",
    "quick export",
    # Edit
    "undo",
    "redo",
    "cut",
    "copy",
    "copy comp",
    "paste",
    "attributes",
    "clear",
    "ripple",
    "duplicate",
    "select all",
    "deselect all",
    "search",
    "original",
    "transition",
    "paste insert",
    # Playback / Transport
    "play",
    "pause",
    "reverse",
    "slow reverse",
    "slow play",
    "play edit",
    "play in to out",
    "play to out",
    "toggle play",
    "play around",
    "step back",
    "step forward",
    "step back five",
    "step forward five",
    "go to sequence start",
    "go to sequence end",
    "go to clip start",
    "go to clip end",
    # Editing tools
    "trim",
    "rip",
    "selection",
    "track select",
    # Track targeting
    "target video one",
    "target video two",
    "target video three",
    "target video four",
    "target video five",
    "target audio one",
    "target audio two",
    "target audio three",
    "target audio four",
    "target audio five",
    "target all video",
    "target all audio",
    "source all video",
    "source all audio",
    "pen",
    "text",
    "slip",
    "roll",
    "stretch",
    "razor",
    "razor all",
    "slide",
    "hand",
    "zoom",
    "zoom in",
    "zoom out",
    "trim edit",
    # Editing operations
    "overwrite",
    "insert",
    "in",
    "out",
    "go to in",
    "go to out",
    "clear in",
    "clear out",
    "clear in and out",
    "lift",
    "extract",
    "add edit",
    "add edit all",
    "nest",
    "group",
    "ungroup",
    "extend",
    "extend edit",
    "extend next",
    "extend previous",
    "ripple trim next",
    "trim next",
    "ripple trim previous",
    "trim previous",
    "trim in to playhead",
    "trim out to playhead",
    "select clip",
    "match",
    "reverse match frame",
    "mark clip",
    "enable",
    "link",
    "unlink selection",
    "link selection",
    "join through edits",
    "gaps",
    "speed",
    "clip speed",
    "subclip",
    "make subclip",

    "subsequence",
    "export frame",
    "apply audio transition",
    "apply both transitions",
    "delete effects",
    "fit frame",
    "fill frame",
    "scale frame",
    "boost",
    "lower",
    "volume up",
    "volume down",
    "next gap",
    "previous gap",
    "zoom to fit",
    "zoom to frame",
    "maximize",
    "nested",
    "snap",
    "multicam",
    "create multicam",
    "sync",
    "sync window",
    "enable multicam",
    "add track",
    "add video track",
    "rename audio track",
    "rename video track",
    "delete tracks",
    "toggle trim type",
    "selection follows playhead",
    "flatten multicam",
    "toggle multicam",
    "multicam audio",
    "rename",
    "reveal in project",
    "open in source monitor",
    # Sequence / Multicam
    "add audio keyframe",
    "add video keyframe",
    "next keyframe",
    "previous keyframe",
    "ease in",
    "ease out",
    "linear keyframe",
    "hold keyframe",
    "increase audio keyframe",
    "decrease audio keyframe",
    "increase video keyframe",
    "decrease video keyframe",
    # Markers
    "marker",
    "green",
    "next marker",
    "previous marker",
    "red",
    "violet",
    "cyan",
    "yellow",
    "orange",
    "marker blue",
    "marker white",
    "clear marker",
    "clear all markers",
    "edit marker",
    "range marker",
    "chapter marker",
    "show markers",
    # Labeled marker triggers (hybrid: Vosk hears keyword, Whisper captures title)
    "red marker",
    "green marker",
    "blue marker",
    "violet marker",
    "orange marker",
    "yellow marker",
    "cyan marker",
    "white marker",
    # Range marker (span)
    "span",
    # Labels
    "no label",
    "label violet",
    "label iris",
    "label caribbean",
    "label lavender",
    "label cerulean",
    "label forest",
    "label rose",
    "label mango",
    "label purple",
    "label blue",
    "label teal",
    "label magenta",
    "label tan",
    "label green",
    "label yellow",
    "label brown",
    # Audio
    "gain",
    "mono",
    "speech",
    "nudge volume down",
    "nudge volume up",
    "nudge volume down three",
    "nudge volume up three",
    "mappings",
    "units",
    # Clip options
    "replace from bin",
    "replace from source",
    "replace",
    "blend",
    "frame sampling",
    "optical flow",
    "render",
    "render replace",
    "restore",
    "freeze",
    "frame hold options",
    "remove attributes",
    "proxies",
    "peaks",
    "interpret",
    "synchronize",
    # Timeline display
    "expand",
    "minimize",
    "increase track height",
    "decrease track height",
    "increase audio height",
    "decrease audio height",
    "work area in",
    "work area out",
    "scrubbing",
    "mutes",
    "solos",
    "sequence label color",
    # Track height presets
    "track height one",
    "track height two",
    "track height three",
    "track height four",
    "track height five",
    "track height six",
    "track height seven",
    "track height eight",
    "track height nine",
    "track height ten",
    "next screen",
    "previous screen",
    # Graphics
    "add text",
    "rectangle",
    "ellipse",
    "enter text edit",
    "layer up",
    "layer down",
    "layer to top",
    "layer to bottom",
    "center",
    # Captions
    "caption",
    "split",
    "merge",
    # Monitor
    "fullscreen",
    "full screen",
    "maximize focused",
    "guides",
    "overlays",
    "program zoom fit",
    "program zoom 100",
    "source zoom fit",
    "source zoom 100",
    # Panels / Windows
    "bin",
    "bin window",
    "source",
    "timeline",
    "preview window",
    "controls",
    "audio mixer",
    "effects",
    "browser",
    "audio clip mixer",
    "open text panel",
    "captions panel",
    # Workspaces
    "workspace one",
    "workspace two",
    "workspace three",
    "workspace four",
    "workspace five",
    "workspace six",
    "workspace seven",
    "workspace eight",
    "workspace nine",
    "revert workspace",
    # Panel navigation
    "next panel",
    "previous panel",
    # Effects panel / calibration
    "find effects",
    "save effect preset",
    "delete all effects",
    "recalibrate",
    "recalibrate search",
    # Effects search
    "blur",
    "cross dissolve",
    "lumetri color",
    "warp stabilizer",
    "wave warp",
    "cross",
    # Pan
    "pan center",
    "pan left",
    "pan right",
    # Multicam cameras
    "camera one",
    "camera two",
    "camera three",
    "camera four",
    "camera five",
    "camera six",
    "camera seven",
    "camera eight",
    "camera nine",
    # tvh
    "ease in out",
    "ease keyframes",
    "ease in and out",
    "close titler",
    "lock",
    "crop",
    "transform",
    "mono left",
    "mono right",
    # Effect Controls panel — click-and-drag value fields (no prefix needed)
    "position x",
    "position y",
    "scale",
    "scale width",
    "uniform scale",
    "rotation",
    "anchor x",
    "anchor y",
    "anti flicker filter",
    "crop left",
    "crop top",
    "crop right",
    "crop bottom",
    "opacity",
    "blend mode",
    "time remapping",
    # ── Video Effects: Color Correction ────────────────────────────────────────
    "asc cdl",
    "brightness and contrast",
    "color balance",
    "tint",
    "video limiter",
    # ── Audio Effects: Amplitude and Compression ────────────────────────────────
    "amplify",
    "channel mixer",
    "channel volume",
    "de esser",
    "dynamics",
    "dynamics processing",
    "hard limiter",
    "multiband compressor",
    "single band compressor",
    "tube modeled compressor",
    # ── Audio Effects: Channel ──────────────────────────────────────────────────
    "balance",
    "binauralizer ambisonics",
    "mute",
    "panner ambisonics",
    "volume",
    # ── Audio Effects: Delay and Echo ───────────────────────────────────────────
    "analog delay",
    "delay",
    "multitap delay",
    # ── Audio Effects: Filter and EQ ────────────────────────────────────────────
    "bandpass",
    "bass",
    "fft filter",
    "graphic equalizer 10 bands",
    "graphic equalizer 20 bands",
    "graphic equalizer 30 bands",
    "highpass",
    "lowpass",
    "notch filter",
    "parametric equalizer",
    "scientific filter",
    "simple notch filter",
    "simple parametric eq",
    "treble",
    # ── Audio Effects: Modulation ───────────────────────────────────────────────
    "chorus flanger",
    "flanger",
    "phaser",
    # ── Audio Effects: Noise Reduction / Restoration ────────────────────────────
    "automatic click remover",
    "de hummer",
    "de noise",
    "de reverb",
    # ── Audio Effects: Reverb ───────────────────────────────────────────────────
    "convolution reverb",
    "studio reverb",
    "surround reverb",
    # ── Audio Effects: Special ──────────────────────────────────────────────────
    "distortion",
    "fill left with right",
    "fill right with left",
    "guitar suite",
    "loudness meter",
    "loudness radar",
    "mastering",
    "swap channels",
    "vocal enhancer",
    # ── Audio Effects: Stereo Imagery ───────────────────────────────────────────
    "stereo expander",
    # ── Audio Effects: Time and Pitch ───────────────────────────────────────────
    "pitch shifter",
    # ── Audio Transitions ───────────────────────────────────────────────────────
    "constant gain",
    "constant power",
    "exponential fade",
    # ── Video Effects: 3D / Generate ──────────────────────────────────────────
    "3d roll",
    "3d rotate",
    "4 color gradient",
    "chaos",
    "stroke",
    "wipe 2",
    "fi soft wipe impacts 2",
    # ── Video Effects: Adjust ──────────────────────────────────────────────────
    "levels",
    "sdr conform",
    # ── Video Effects: Blur & Sharpen ──────────────────────────────────────────
    "bokeh blur",
    "camera blur",
    "compound blur",
    "directional blur",
    "focus blur",
    "gaussian blur",
    "unsharp mask",
    # ── Video Effects: Channel ─────────────────────────────────────────────────
    "invert",
    # ── Video Effects: Color Correction ───────────────────────────────────────
    "color balance",
    "gamma correction",
    # ── Video Effects: Distort ─────────────────────────────────────────────────
    "basic 3d",
    "corner pin",
    "lens distortion",
    "magnify",
    "mirror",
    "offset",
    "turbulent displace",
    "twirl",
    "wave warp",
    # ── Video Effects: Generate ────────────────────────────────────────────────
    "checkerboard",
    "lens flare",
    "lightning",
    "ramp",
    # ── Video Effects: Image Control ───────────────────────────────────────────
    "black and white",
    "color emboss",
    "color pass",
    "color replace",
    "filmstocks",
    "monochrome",
    # ── Video Effects: Keying ─────────────────────────────────────────────────
    "alpha adjust",
    "color key",
    "luma key",
    "track matte key",
    "ultra key",
    # ── Video Effects: Stylize ────────────────────────────────────────────────
    "alpha glow",
    "brush strokes",
    "color emboss",
    "find edges",
    "roughen edges",
    "texture",
    "threshold",
    "write on",
    # ── Video Effects: Transform ──────────────────────────────────────────────
    "auto reframe",
    "crop",
    "edge feather",
    "horizontal flip",
    "vertical flip",
    "rolling shutter repair",
    "rounded crop",
    # ── Video Effects: Utility ────────────────────────────────────────────────
    "cineon converter",
    "metadata and timecode burn in",
    "reduce interlace flicker",
    # ── Video Effects: Video ──────────────────────────────────────────────────
    "simple text",
    "timecode",
    # ── Video Effects: Misc ───────────────────────────────────────────────────
    "alpha adjust",
    "auto align",
    "block dissolve",
    "burn alpha",
    "burn chroma",
    "camera shake",
    "center split",
    "checker wipe",
    "chroma leak",
    "cinematic",
    "clock wipe",
    "clone",
    "color emboss",
    "cross zoom",
    "dip to black",
    "dip to white",
    "drop shadow",
    "echo glow",
    "edge glow",
    "film roll",
    "flash",
    "frame",
    "glint",
    "gradient wipe",
    "immersive video",
    "inset",
    "iris",
    "iris box",
    "iris cross",
    "iris diamond",
    "iris round",
    "lens flare",
    "levels",
    "logo cutout",
    "long shadow",
    "luma key",
    "magnify",
    "mirror",
    "morph cut",
    "page turn",
    "paint splatter",
    "pips",
    "radial wipe",
    "random blocks",
    "random wipe",
    "rgb split",
    "sdr conform",
    "shrink",
    "spacer",
    "spiral boxes",
    "turbulent displace",
    "twirl",
    "twirls",
    "venetian blinds",
    "vignette",
    "volumetric rays",
    "wedge wipe",
    "whip",
    "wiggle",
    # ── Video Transitions: Wipe ────────────────────────────────────────────────
    "band slide",
    "band wipe",
    "barn doors",
    "checker wipe",
    "clock wipe",
    "gradient wipe",
    "paint splatter",
    "radial wipe",
    "random blocks",
    "random wipe",
    "spiral boxes",
    "venetian blinds",
    "wedge wipe",
    "whip",
    # ── Video Transitions: Iris ────────────────────────────────────────────────
    "iris box",
    "iris cross",
    "iris diamond",
    "iris round",
    # ── Video Transitions: Dissolve ────────────────────────────────────────────
    "additive dissolve",
    "dip to black",
    "dip to white",
    # ── Video Transitions: Slide ───────────────────────────────────────────────
    "band slide",
    "center split",
    "push",
    "slash slide",
    "split",
    # ── Video Transitions: Zoom ────────────────────────────────────────────────
    "cross zoom",
    # ── Film Impact Shortcuts (F1–F10) ─────────────────────────────────────────
    "f1 blur fx",
    "f1 bokeh blur fx",
    "f1 auto align fx",
    "f1 3d rotate fx",
    "f2 camera shake fx",
    "f2 channel mix fx",
    "f2 compound blur fx",
    "f2 logo cutout",
    "f3 clone fx",
    "f3 echo glow fx",
    "f3 grow fx",
    "f3 long shadow fx",
    "f4 edge glow fx",
    "f4 move fx",
    "f4 music fx",
    "f5 focus blur fx",
    "f5 rounded crop fx",
    "f5 shrink fx",
    "f6 glint fx",
    "f6 spacer fx",
    "f6 stroke fx",
    "f7 light leaks fx",
    "f7 spin fx",
    "f7 vignette fx",
    "f8 rgb split fx",
    "f8 wiggle fx",
    "f9 volumetric rays fx",
    "f10 wonder glow fx",
    # ── Film Impact Transitions ────────────────────────────────────────────────
    "fi 3d roll impacts",
    "fi 3d spin impacts",
    "fi block motion impacts",
    "fi blur dissolve impacts",
    "fi blur to color impacts",
    "fi burn alpha impacts",
    "fi burn chroma impacts",
    "fi chaos impacts",
    "fi chroma leak impacts",
    "fi clock wipe impacts",
    "fi directional blur impacts",
    "fi dissolve impacts",
    "fi earthquake impacts",
    "fi film roll impacts",
    "fi flare impacts",
    "fi flash impacts",
    "fi flicker impacts",
    "fi flip motion impacts",
    "fi fold motion impacts",
    "fi frame impacts",
    "fi glass impacts",
    "fi glow impacts",
    "fi grunge impacts",
    "fi kaleidoscope impacts",
    "fi lens blur impacts",
    "fi light leak impacts",
    "fi light sweep impacts",
    "fi linear wipe impacts",
    "fi liquid distortion impacts",
    "fi louver impacts",
    "fi luma fade impacts",
    "fi mirror impacts",
    "fi mosaic impacts",
    "fi motion camera",
    "fi motion tween",
    "fi neon wipe impacts",
    "fi page peel impacts",
    "fi panel wipe impacts",
    "fi phosphor impacts",
    "fi plateau wipe impacts",
    "fi pop motion impacts",
    "fi pull motion impacts",
    "fi push impacts",
    "fi radial blur impacts",
    "fi ray impacts",
    "fi roll impacts",
    "fi shape flow",
    "fi slice impacts",
    "fi soft wipe impacts",
    "fi solarize impacts",
    "fi spin motion impacts",
    "fi split impacts",
    "fi spring motion impacts",
    "fi star wipe impacts",
    "fi stretch impacts",
    "fi stretch wipe impacts",
    "fi stripe impacts",
    "fi text animator",
    "fi travel motion impacts",
    "fi tv power impacts",
    "fi typewriter impacts",
    "fi vhs damage impacts",
    "fi wave impacts",
    "fi zoom blur impacts",
    "film impact essentials",
    "film impact lights and blurs",
    "film impact smart tools",
    "film impact transformers",
    "fi glitch impacts",
    # ── tvh: parameterized prefixes (handled in processVoiceInput) ─────────────
    # "gain <n>"        → add_gain(n)         e.g. "gain seven" / "gain 7"
    # "boost <n>"       → add_gain(n)         alias for gain
    # "add gain <n>"    → add_gain(n)
    # "scrub <param>"   → instant_vfx(param)  e.g. "scrub scale" / "scrub rotation"
    # "adjust <param>"  → instant_vfx(param)
    # "preset <name>"   → preset(name)        e.g. "preset crop 50"
    # "apply preset <n>"→ preset(name)
    # "save clip <n>"   → save_clipboard(n)   needs InsideClipboard.exe
    # "recall clip <n>" → recall_clipboard(n) needs InsideClipboard.exe
    # "paste clip <n>"  → recall_clipboard(n)
]
